version: '3.8'
services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    command: ["./wait-for-db.sh", "npm", "run", "start"]
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - default
    ports:
      - 3000:3000
    env_file:
      - app.env
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next

  db:
    container_name: db
    image: postgres:12
    restart: unless-stopped
    networks:
      - default
    ports:
      - 5432:5432
    env_file:
      - db.env
    volumes:
      - "./db:/docker-entrypoint-initdb.d:delegated"

networks:
  default:
